AWSTemplateFormatVersion: 2010-09-09
Description: cloudformation template to create a s3 bucket which will host the website

Resources:
  WebSite:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebSite
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:DeleteObject"
              - "s3:ListBucket"
            Effect: Allow
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref WebSite
                - /*
            Principal: "*"
Outputs:
  WebsiteURL:
    Value: !Join ['', ['http://', !Ref WebSite, '.s3-website-', !Ref 'AWS::Region', '.amazonaws.com']]