name: Deployment
on:
  push:
    branches:
      - master
jobs:
  test:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3 
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: test
        run: echo ${{ secrets.TEST }}
      - name: build project
        run: npm run build
      - name: setup aws configurations
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE }}
          aws-region: ap-south-1
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: deploy to s3
        run: aws s3 sync ./dist/. s3://todoapp-website-pifc2eya2zf2
          

